defaults:
  - trainer: default
padding_side: "right"
evil: false
truncation_side: "right"
model: "t5-base"
log_dir: "safetyfiles"
log_wandb: true
wandb_entity: "shahules786"
max_length: 512
per_digit_tokens: False
special_tokens:
  eos_token: "</s>"
  sep_token: "<sep>"
  pad_token: "<pad>"
train_dataset:
  name: ["allenai/prosocial-dialog"]
  splits: [["train", "validation"]]
  confidence:
test_dataset:
  name: ["allenai/prosocial-dialog"]
  splits: [["test"]]
  confidence:
